"use strict";
let mypage;
mypage = null;
console.log(mypage);
let myname = "azhar";
console.log(myname);
let myagg;
myagg = 25;
// console.log(myagg.tolowercase);
let myage = "dont know";
console.log(myage);
console.log(myage.toString());
console.log(myage.toLowerCase());
console.log(myage.toUpperCase());
let newage = Math.random() > 0.6 ? "khan" : 60;
console.log(newage);
let age;
age = 90;
age = "dead";
age = "unknown";
age = "living";
