"use strict";
let favoriteColor = "Blue";
let is_animal = "snake";
let FamousScientist = "Pascal ";
console.log("The famous scientist " + FamousScientist + " watched the " + is_animal + " whose color is " + favoriteColor + ".");
console.log(`The famous scientist ${FamousScientist} watched the ${is_animal} whose color is ${favoriteColor}.`);
console.log(favoriteColor);
console.log(FamousScientist);
const MyName = "Syed Akber Shah";
console.log(MyName);
