console.log("Hello World");
console.log("Thanks Governor Sindh Kamran Khan Tessori");
console.log('Hi Akber');
console.log('console');
var myName = "Syed Akber Shah";
// type interference
var My_first_Name = "Syed";
console.log(My_first_Name);
var CompanyName = 'Shah Enterprises';
console.log(CompanyName);
var myAge = "23";
console.log(myAge);
var my_age_exact = 22 + 3;
console.log(my_age_exact);
var MyMarks = 90;
console.log(MyMarks);
console.log(25 < 15);
console.log('Japan' == 'America');
console.log(2 + 3 == 1);
console.log(5 - 4 == 1);
console.log("America" == "America");
console.log(25 > 15);
var user_name = "Azhar";
console.log(user_name == "Akber");
var ownerName = "Asad";
ownerName = "Akber";
console.log(ownerName);
ownerName = "Zaheer";
ownerName = "Zahid";
var pin = 123;
console.log(user_name == "Azhar");
console.log(pin == 456);
var password = true;
console.log(password == pakistan786);
var FactoryName = Azhar123;
console.log(FactoryName);
